DEBUG 2020-07-31 18:43:07.173 UTC: 	 CRAB Client version: v3.200531
DEBUG 2020-07-31 18:43:07.173 UTC: 	 Running on: Linux lxplus738.cern.ch 3.10.0-1127.10.1.el7.x86_64 #1 SMP Wed Jun 3 14:28:03 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2020-07-31 18:43:07.188 UTC: 	 OpenSSl version: OpenSSL 1.0.2k-fips  26 Jan 2017 (Library: OpenSSL 1.0.2d-fips 9 Jul 2015)
DEBUG 2020-07-31 18:43:07.188 UTC: 	 Executing command: 'status'
DEBUG 2020-07-31 18:43:07.192 UTC: 	 Found CRAB cache file /afs/cern.ch/user/p/pgardner/.crab3
ERROR 2020-07-31 18:43:07.215 UTC: 	 Error: 20200731_042045 is not a valid CRAB project directory.
ERROR 2020-07-31 18:43:07.216 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200531.00/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200531.00/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200531.00/lib/CRABClient/Commands/status.py", line 41, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200531.00/lib/CRABClient/Commands/SubCommand.py", line 278, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200531.00/lib/CRABClient/Commands/SubCommand.py", line 619, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: 20200731_042045 is not a valid CRAB project directory.
INFO 2020-07-31 18:43:07.220 UTC: 	 Log file is /afs/cern.ch/user/p/pgardner/CMSSW_10_3_3_patch1/src/HeavyIonsAnalysis/TrackAnalysis/python/crab.log
